### PR TITLE
rename python-magic to python-file, fix provided and add conflicts

### PR DESCRIPTION
**Pull request by AngryPenguinPL**

### CODE REVIEW

**Comment by tpgxyz** [comment]
Please make sure that version of concurrent python-magic is not lower than you set as obsoletes.

Conflicting without versioning is not so good either.

**Comment by AngryPenguinPL** [comment]
Anyway "new" python-magic need epoch or other fix to availd failing tests because its version is lesser than version from magic from file. Maybe I should rename it to python-python-magic just like in Mageia?

**Comment by tpgxyz** [comment]
You have introduced self-conflicts. I'd suggest to drop these as file's magic and python-magic does not conflicts on provided file names.

```
Obsoletes:      python-magic < 5.39-3
Conflicts:      python-magic >= 0.4.18
```

Please rename python bindings to real internal name "file-magic"

**Comment by AngryPenguinPL** [comment]
Now should be ok. Right?

**Comment by tpgxyz** [comment]
LGTM

**Comment by AngryPenguinPL** [comment]
Thanks

**Pull request merged**
